### ISSUE TITLE
[Feature request] Improved layout

### ISSUE THREAD

**Issue by RowanDDR** [bazzinotti/snestracker#142]
**Implementing the upcoming new UI is a big job - how about an intermediate layout refresh that's a bit easier to achieve?**

Let's make things more visually intuitive, in the following ways:
- Group the `INSTRUMENT EDITOR` button with the instruments box.
- Group the `SAMPLE EDITOR` button with the samples box.
- Group the `SONG LENGTH` field with the song box.
- Group the `PATTERN LENGTH` button with the pattern sequence box.
- Group the `PATTERN SEQUENCE` box with the pattern field.
- Some housekeeping – rename various buttons:
 SNG SETT. → SONG SETTINGS
 INST. ED. → INSTRUMENT EDITOR
 SAMP. ED. → SAMPLE EDITOR
 SLEN → SONG LENGTH
 SPD → SPEED(?)
- Deliberate equal spacing between the 4 main boxes, to better define each one as separate entities.

I made 3 difficulty levels – choose your destiny!

<details>
<summary><strong>[EASY] 🍒</strong> <i>(click to expand)</i></summary>
<img src="https://user-images.githubusercontent.com/6626459/90977928-9396f400-e541-11ea-9684-302dfc4864f4.png">
</details>

<details>
<summary><strong>[MEDIUM] 🍒🍒</strong> <i>(click to expand)</i></summary>
<img src="https://user-images.githubusercontent.com/6626459/90977930-9abe0200-e541-11ea-807f-fd5a8e94fa8f.png">
</details>

<details>
<summary><strong>[HARD] 🍒🍒🍒</strong> <i>(click to expand)</i></summary>
<img src="https://user-images.githubusercontent.com/6626459/91064638-69b7fd00-e627-11ea-9f61-123a59ca382d.png">
</details>

**Comment by RowanDDR** [comment]
🥇**Well done and congratulations** for successfully tackling HARD difficulty level! Feel free to close this, as its served its purpose. However, for the record, some minor outstanding stuff you may like to polish off for next release - if they are easily achievable:

- Background colour of window: in the mockup I made this dark grey (#1c1c1c) instead of black. (inside the main tracker box is still black (#000000). I thought this makes the interface seem a bit more friendly and cosy.

- Odd looking empty space at end of window - in the mockup I cropped this off as it didn't seem to serve any purpose and was taking up space.

- If you're not a fan of the yellow for the box headings, consider another colour? I was just trying to give these headings some prominence and better sense of hierarchy for each box contents.

- You could move SLEN into the "SONG SETTINGS" dialog box instead of deleting it.

**Comment by bazzinotti** [comment]
Thanks for the medal!! ^_^ I feel appreciated!

"Background Color of Window" - Maybe I'll play around with it. :) 

" Box Headings " - Maybe I'll play around with this too! The size of the font is a bit of an obstacle right now, so I will prioritize other issues before we get higher font customization. 

"SLEN" - I think it was unnecessary afterall, eg. Not a single scenario where it was useful.

thanks Rowan!!

P.S. I leave the issues labeled "closed in early-paid" etc. to inform passers by that these things are only fixed in the early release on Patreon. If I close this before releasing to Github, it becomes hidden for the most part. I'll close later ;)
