### ISSUE TITLE
[Feature request] Add recently opened files to FILE menu

### ISSUE THREAD

**Issue by RowanDDR** [bazzinotti/snestracker#84]
Add a list of recently opened files to FILE menu? Latest 5 or so? It would be really handy. That's all! 🤓

**Comment by bazzinotti** [comment]
I agree! Plus, I've already implemented such a feature in my fork of [bsnes-classic](https://github.com/bazzinotti/bsnes-classic) (see screenshot below), so it should be relatively simple to incorporate. Technical details follow.

The `Context_Menu` class will have to be improved to allow nested navigation, so it can behave like the following:

![Screen Shot 2020-06-20 at 4 09 13 AM](https://user-images.githubusercontent.com/2224787/85196964-da4f4000-b2ab-11ea-878f-7d9d9ca93cc2.png)

**Comment by RowanDDR** [comment]
Personally I find it even easier when recent file list appears on the 1st dropdown menu, not nested in a 2nd one, as its a bit fiddely (especially if you're drunk). So in your screenshot, they would appear in the 1st menu underneath the line "Controller Port 2", with a heading "Recent files".

But either way, it would be fab. Just giving my 2 cents.

**Comment by bazzinotti** [comment]
Haha, right. Well that is convenient for me because it would be easier to implement them on the same drop-down. So that makes it easier, thanks!

I'm suggesting to myself how to display the filepath without showing the whole path. This was good inspiration:
![Screen Shot 2020-07-01 at 10 19 54 PM](https://user-images.githubusercontent.com/2224787/86309169-1312e180-bbe9-11ea-9384-e257dec9dcfa.png)

Note in particular how the app handles identical file names but in different folders. It is displayed in a tidy manner.
